-- Create stores table
CREATE TABLE IF NOT EXISTS stores (
    id SERIAL PRIMARY KEY,
    store_id TEXT,
    images TEXT,
    dispatch_code TEXT,
    dispatch_store_name TEXT,
    store_code TEXT,
    store_company TEXT,
    store_name TEXT,
    address_line TEXT,
    city TEXT,
    county TEXT,
    eircode TEXT,
    latitude TEXT,
    longitude TEXT,
    route TEXT,
    door_code TEXT,
    alarm_code TEXT,
    fridge_code TEXT,
    keys_available TEXT,
    key_code TEXT,
    prior_registration_required TEXT,
    hour_access_24 TEXT,
    earliest_delivery_time TEXT,
    opening_time_saturday TEXT,
    opening_time_bankholiday TEXT,
    -- Added delivery days columns
    delivery_monday TEXT DEFAULT 'No',
    delivery_tuesday TEXT DEFAULT 'No',
    delivery_wednesday TEXT DEFAULT 'No',
    delivery_thursday TEXT DEFAULT 'No',
    delivery_friday TEXT DEFAULT 'No',
    delivery_saturday TEXT DEFAULT 'No'
); 